### ISSUE TITLE
Refactor TODO's

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/amigo_whole_body_controller#2]
- [ ] remove `fix_pose` from every component (it's ugly)
- [ ] put the `RefInterpolator` in it's own package
- [ ] rewrite `JointTrajectory` not not use pointers
- [ ] convert `FCL Result` in the `Distance` object to `Eigen`
- [ ] remove the `Bullet` library
- [ ] move the cartesian impedance markers into the motion objective (instead of the python client)
- [ ] move all headers that are private to the src folder
